services:
  accounts:
    image: "meghamala228/accounts:1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
  loans:
    image: "meghamala228/loans:1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
  cards:
    image: "meghamala228/cards:1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
networks:
  springbank:
    driver: "bridge"