spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud: # telling gateway server to connect to discovery server to locate all MS
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true # telling gateway server to accept lower case service name
      http-client:
        connect-timeout: 1000
        response-timeout: 2s

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*" # to enable and expose all endpoints supported by springboot actuator
        # ex: http://localhost:8090/actuator/refresh will b exposed for loans
  endpoint: # gateway server
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "spring bank gateway server application"
    version: "1.0.0"

logging:
  level:
    com:
      springbank:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default: # for all kinds of circuit breaker
      slidingWindowSize: 10 #monitor atleast 10 reqs coming to AC service
      permittedNumberOfCallsInHalfOpenState: 2 #partial traffic in half open
      failureRateThreshold: 50 # atleast 50% of reqs are failed : move to closed state
      waitDurationInOpenState: 10000 # wait 10 secs in open state before moving to half open