server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:mysql://localhost:3308/loansdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq: # spring cloud bus config with rabbitmq for refresh config
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*" # to enable and expose all endpoints supported by springboot actuator, refresh/busrefresh
  endpoint: # to deregister from eureka during shutdown
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # to make accounts MS register with eureka using IP address
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "loans"
    description: "spring bank loans application"
    version: "1.0.0"