server:
  port: 8080
spring:
  application:
    name: "accounts"  # name has to be same as config file name: accounts.yml
  profiles:
    active: "prod" # by default which profile to consider
  datasource:
#    url: jdbc:mysql://localhost:3306/accountsdb
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always # to make sure to run the script in schema.sql during startup
  config:
    import: "optional:configserver:http://localhost:8071/"  # this is client so need to give endpoint of config server , optional to
    # indicate to start MS even if config server is unavailable
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # to enable and expose all endpoints supported by springboot actuator
        # ex: http://localhost:8090/actuator/refresh will b exposed for loans
  health: # /actuator/health should be called to get the health status, as gateway server depends on all 3 MS
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint: # to deregister from eureka during shutdown
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true # to make accounts MS register with eureka using IP address
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "spring bank accounts application"
    version: "1.0.0"

logging:
  level:
    com:
      springbank:
        accounts: DEBUG

resilience4j.circuitbreaker:
  configs:
    default: # for all kinds of circuit breaker
      slidingWindowSize: 10 #monitor atleast 10 reqs coming to AC service
      permittedNumberOfCallsInHalfOpenState: 2 #partial traffic in half open
      failureRateThreshold: 50 # atleast 50% of reqs are failed : move to closed state
      waitDurationInOpenState: 10000 # wait 10 secs in open state before moving to half open