services:
  rabbit: # for msg broadcasting, need to run rabbit service docker
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "meghamala228/configserver:2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on: # config server depends on rabbit
      rabbit:
        condition: service_healthy
    healthcheck: # to check if service is started or not
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "meghamala228/accounts:2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment: # linking client to server
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    image: "meghamala228/loans:2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    image: "meghamala228/cards:2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  springbank:
    driver: "bridge"