services:
  configserver:
    image: "meghamala228/configserver:2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
  accounts:
    image: "meghamala228/accounts:2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
    environment: # linking client to server
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # service name is configserver
      SPRING_PROFILES_ACTIVE: default
  loans:
    image: "meghamala228/loans:2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # service name is configserver
      SPRING_PROFILES_ACTIVE: default
  cards:
    image: "meghamala228/cards:2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - springbank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" # service name is configserver
      SPRING_PROFILES_ACTIVE: default
networks:
  springbank:
    driver: "bridge"