spring:
  application: # name for config server
    name: "configserver"
  profiles:
    # active: native # activate native profile of config server( for class and file path)
    active: git
  cloud:
    config:
      server:
        #native:
          # search-locations: "classpath:/config" # classpath config
          #search-locations: "file:///Users//meghamala//Documents//config"
        git:
          uri: "https://github.com/Meghamala/springBank-config.git"
          default-label: main # branch name
          timeout: 5 # wait for 5 sec or throw exception
          clone-on-start: true #to clone for first request
          force-pull: true
  rabbitmq: # spring cloud bus config with rabbitmq for refresh config
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health: # /actuator/health should be called to get the health status
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

