services:
  network-deploy-service: # network service
    networks:
      - springbank

  microservice-base-config: # base service ( for rabbit and config server)
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
      environment:
        SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config: # config service for all MS
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/